// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using w_list.Data;

namespace w_list.Migrations
{
    [DbContext(typeof(WListContext))]
    [Migration("20200508022858_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("w_list.Models.ForumModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AllowedWord1")
                        .HasColumnType("TEXT");

                    b.Property<string>("AllowedWord10")
                        .HasColumnType("TEXT");

                    b.Property<string>("AllowedWord2")
                        .HasColumnType("TEXT");

                    b.Property<string>("AllowedWord3")
                        .HasColumnType("TEXT");

                    b.Property<string>("AllowedWord4")
                        .HasColumnType("TEXT");

                    b.Property<string>("AllowedWord5")
                        .HasColumnType("TEXT");

                    b.Property<string>("AllowedWord6")
                        .HasColumnType("TEXT");

                    b.Property<string>("AllowedWord7")
                        .HasColumnType("TEXT");

                    b.Property<string>("AllowedWord8")
                        .HasColumnType("TEXT");

                    b.Property<string>("AllowedWord9")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Locked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ForumModel");
                });
#pragma warning restore 612, 618
        }
    }
}
